---
# defaults file for libvirt-provision
#

# By default will run the role to create VMs
# Values can be one of: ['create', 'delete']
libvirt_vm_state: create

libvirt_images_folder: /var/lib/libvirt/images
libvirt_base_image: Ubuntu-14.04-64-cons.qcow2
libvirt_user: qemu
# MAC prefix should only contain 6 digits, the other 6 digits will be dynamically
# generated
libvirt_mac_prefix: '52:54:00'

libvirt_dns_server: 172.16.110.254
libvirt_dns_key: /etc/rndc.key
libvirt_dns_zone: dom110.u13.org

# Ip prefix used for newly created VMs
libvirt_ip_prefix: '172.16.110'

libvirt_bridge: ccm

libvirt_vms:
  ansible-test:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.10"
