################################################################################
# > Playbook used to delete VMs running with KVM/QEMU
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Delete VMs
  hosts: localhost
  connection: local
  become: yes

  roles:
    - role: Lowess.libvirt
      libvirt_vm_state: delete
