################################################################################
# > Playbook used to configure webservers
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure webservers
  hosts: webservers
  become: yes

  roles: []
